spring.application.name=bank_project
server.port=${port:8082}

spring.datasource.url=jdbc:mysql://${DB_host}:${DB_port}/${DB_name}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_User}
spring.datasource.password=${DB_Password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.enabled=true

app.admin.email=bankadmin@gmail.com
app.admin.password=platinumbank@9732

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_User}
spring.mail.password=${MAIL_Password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
